disabled_rules:
- line_length
- trailing_whitespace
- switch_case_alignment

opt_in_rules:


function_parameter_count:
    warning: 10
    error: 15

file_length:
    warning: 500

type_body_length:
    warning: 400
    error: 450

reporter: xcode


warning_threshold: 15
